version: '3'

services:
  app:
    build: .
    container_name: express_app
    ports:
      - "3000:3000"    # Optional: expose for debugging
    

  nginx:
    image: nginx:latest
    container_name: nginx_server
    ports:
      - "8081:80"     # Map host port 8080 to container port 80
    volumes:
      - ./nginx/default.conf:/etc/nginx/default.conf
    depends_on:
      - app
    