 
services:
  app:
    build: 
      context: .
    container_name: express_app
    ports:
      - "3000:3000"
    networks:
      - app_network

  nginx:
    image: nginx:latest
    container_name: nginx_server
    ports:
      - "8000:8000"
    volumes:
      - ./nginx.conf:/etc/nginx/default.conf
    depends_on:
      - app
    networks:
      - app_network

networks:
  app_network:
    driver: bridge