version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: express_app
    restart: always
    expose:
      - 3000

  nginx:
    image: nginx:alpine
    container_name: nginx_server
    ports:
      - "8081:80"
    volumes:
      - ./nginx.conf:/etc/nginx/default.conf
    depends_on:
      - app